task-order.log.2014-10-23:2014-10-23 14:18:37,509 - madeira.task - ERROR - PROCESS Q2014102311560000000002 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) 1054 (42S22): Unknown column 'product' in 'field list' 'INSERT INTO order_100001 (order_id, user_id, price, mobile, sp_order_id, req_time, resp_time, back_time, result, back_result, value, balance, area, product) VALUES (%(order_id)s, %(user_id)s, %(price)s, %(mobile)s, %(sp_order_id)s, %(req_time)s, %(resp_time)s, %(back_time)s, %(result)s, %(back_result)s, %(value)s, %(balance)s, %(area)s, %(product)s)' {'result': '5003', 'order_id': 'Q2014102311534000000001', 'back_time': None, 'mobile': '13805172668', 'sp_order_id': 'Q20141023115328', 'req_time': datetime.datetime(2014, 10, 23, 11, 53, 40), 'area': '1:JS', 'balance': None, 'value': None, 'user_id': '100001', 'price': 0, 'resp_time': datetime.datetime(2014, 10, 23, 11, 53, 40), 'back_result': None, 'product': None}
Q2014102311560000000002 测试数据，数据已丢失
task-order.log.2014-11-14:2014-11-14 10:24:22,880 - madeira.task - ERROR - PROCESS Q2014111410242010000212 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) 1146 (42S02): Table 'madeira.order_101103' doesn't exist 'INSERT INTO order_101103 (order_id, user_id, price, mobile, sp_order_id, req_time, resp_time, back_time, result, back_result, value, balance, area, product) VALUES (%(order_id)s, %(user_id)s, %(price)s, %(mobile)s, %(sp_order_id)s, %(req_time)s, %(resp_time)s, %(back_time)s, %(result)s, %(back_result)s, %(value)s, %(balance)s, %(area)s, %(product)s)' {'result': '10007', 'mobile': 'None', 'back_time': None, 'user_id': '101103', 'sp_order_id': 'None', 'area': 'None:None', 'price': 0, 'product': 'None', 'req_time': datetime.datetime(2014, 11, 14, 10, 24, 16), 'back_result': None, 'value': None, 'resp_time': datetime.datetime(2014, 11, 14, 10, 24, 16), 'order_id': 'Q2014111410241610000211', 'balance': None}
Q2014111410242010000212 无效数据
task-order.log.2014-11-25:2014-11-25 12:34:49,510 - madeira.task - ERROR - PROCESS Q2014112512344310000774 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) 1048 (23000): Column 'result' cannot be null 'INSERT INTO order_101103 (order_id, user_id, price, mobile, sp_order_id, req_time, resp_time, back_time, result, back_result, value, balance, area, product) VALUES (%(order_id)s, %(user_id)s, %(price)s, %(mobile)s, %(sp_order_id)s, %(req_time)s, %(resp_time)s, %(back_time)s, %(result)s, %(back_result)s, %(value)s, %(balance)s, %(area)s, %(product)s)' {'result': None, 'mobile': '13191311314', 'back_time': None, 'user_id': '101103', 'sp_order_id': '200252678220141125123303001370', 'area': '2:NM', 'price': 10, 'product': 'data', 'req_time': datetime.datetime(2014, 11, 25, 12, 34, 49), 'back_result': None, 'value': None, 'resp_time': None, 'order_id': 'Q2014112512344910000775', 'balance': None}
Q2014112512344310000774 异常数据 越亮传奇 无法修复
task-order.log.2014-11-25:2014-11-25 12:34:49,511 - madeira.task - ERROR - PROCESS Q2014112512344110000773 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) 1048 (23000): Column 'result' cannot be null 'INSERT INTO order_101103 (order_id, user_id, price, mobile, sp_order_id, req_time, resp_time, back_time, result, back_result, value, balance, area, product) VALUES (%(order_id)s, %(user_id)s, %(price)s, %(mobile)s, %(sp_order_id)s, %(req_time)s, %(resp_time)s, %(back_time)s, %(result)s, %(back_result)s, %(value)s, %(balance)s, %(area)s, %(product)s)' {'result': None, 'mobile': '13191311314', 'back_time': None, 'user_id': '101103', 'sp_order_id': '200252678220141125123303001370', 'area': '2:NM', 'price': 10, 'product': 'data', 'req_time': datetime.datetime(2014, 11, 25, 12, 34, 49), 'back_result': None, 'value': None, 'resp_time': None, 'order_id': 'Q2014112512344910000775', 'balance': None}
Q2014112512344110000773 在途单保存失败，完工单保存成功，不需要修复 越亮传奇
task-order.log.2014-11-26:2014-11-26 09:46:37,689 - madeira.task - ERROR - PROCESS Q2014112609463010001005 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) 1048 (23000): Column 'result' cannot be null 'INSERT INTO order_101103 (order_id, user_id, price, mobile, sp_order_id, req_time, resp_time, back_time, result, back_result, value, balance, area, product) VALUES (%(order_id)s, %(user_id)s, %(price)s, %(mobile)s, %(sp_order_id)s, %(req_time)s, %(resp_time)s, %(back_time)s, %(result)s, %(back_result)s, %(value)s, %(balance)s, %(area)s, %(product)s)' {'result': None, 'mobile': '15598921109', 'back_time': None, 'user_id': '101103', 'sp_order_id': '200252678220141126094447001625', 'area': '2:NM', 'price': 10, 'product': 'data', 'req_time': datetime.datetime(2014, 11, 26, 9, 46, 34), 'back_result': None, 'value': None, 'resp_time': None, 'order_id': 'Q2014112609463410001006', 'balance': None}
Q2014112609463010001005 在途单保存失败，完工单保存成功，不需要修复 越亮传奇

task-order.log.2014-12-05:2014-12-05 09:14:47,174 - madeira.task - ERROR - PROCESS Q2014120509112410003130 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) 1146 (42S02): Table 'madeira.up_order_700116' doesn't exist 'INSERT INTO up_order_700116 (stage, order_id, up_order_id, route, price, cost, up_cost, up_req_time, up_resp_time, up_back_time, up_result, up_back_result) VALUES (%(stage)s, %(order_id)s, %(up_order_id)s, %(route)s, %(price)s, %(cost)s, %(up_cost)s, %(up_req_time)s, %(up_resp_time)s, %(up_back_time)s, %(up_result)s, %(up_back_result)s)' {'price': 15, 'order_id': 'Q2014120509111510003129', 'stage': 1, 'cost': 142500, 'up_back_result': '00000', 'route': '21cn', 'up_order_id': 'Q2014120509111510003129', 'up_result': '0', 'up_back_time': datetime.datetime(2014, 12, 5, 9, 14, 41), 'up_cost': '142500', 'up_resp_time': datetime.datetime(2014, 12, 5, 9, 11, 15), 'up_req_time': datetime.datetime(2014, 12, 5, 9, 11, 15)}
Q2014120509112410003130 回单数据丢失，需要手工补数据 李嘉诚（700109）

task-order.log.2014-12-05:2014-12-05 10:50:57,157 - madeira.task - ERROR - PROCESS Q2014120510505310003197 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) 1146 (42S02): Table 'madeira.up_order_700116' doesn't exist 'INSERT INTO up_order_700116 (stage, order_id, up_order_id, route, price, cost, up_cost, up_req_time, up_resp_time, up_back_time, up_result, up_back_result) VALUES (%(stage)s, %(order_id)s, %(up_order_id)s, %(route)s, %(price)s, %(cost)s, %(up_cost)s, %(up_req_time)s, %(up_resp_time)s, %(up_back_time)s, %(up_result)s, %(up_back_result)s)' {'price': 30, 'order_id': 'Q2014120510160610003176', 'stage': 1, 'cost': 285000, 'up_back_result': '00000', 'route': '21cn', 'up_order_id': 'Q2014120510160610003176', 'up_result': '0', 'up_back_time': datetime.datetime(2014, 12, 5, 10, 50, 47), 'up_cost': '285000', 'up_resp_time': datetime.datetime(2014, 12, 5, 10, 16, 6), 'up_req_time': datetime.datetime(2014, 12, 5, 10, 16, 6)}
Q2014120510505310003197 在途单保存失败，完工单保存成功，不需要修复 Shunyi（order_700111）
task-order.log.2014-12-05:2014-12-05 11:22:19,790 - madeira.task - ERROR - PROCESS Q2014120511221710003207 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) 1146 (42S02): Table 'madeira.up_order_700116' doesn't exist 'INSERT INTO up_order_700116 (stage, order_id, up_order_id, route, price, cost, up_cost, up_req_time, up_resp_time, up_back_time, up_result, up_back_result) VALUES (%(stage)s, %(order_id)s, %(up_order_id)s, %(route)s, %(price)s, %(cost)s, %(up_cost)s, %(up_req_time)s, %(up_resp_time)s, %(up_back_time)s, %(up_result)s, %(up_back_result)s)' {'price': 15, 'order_id': 'Q2014120511025510003204', 'stage': 1, 'cost': 142500, 'up_back_result': '00000', 'route': '21cn', 'up_order_id': 'Q2014120511025510003204', 'up_result': '0', 'up_back_time': datetime.datetime(2014, 12, 5, 11, 22, 13), 'up_cost': '142500', 'up_resp_time': datetime.datetime(2014, 12, 5, 11, 2, 55), 'up_req_time': datetime.datetime(2014, 12, 5, 11, 2, 55)}
Q2014120511221710003207 在途单保存失败，完工单保存成功，不需要修复 Niujq（order_700113）
task-order.log.2014-12-05:2014-12-05 14:55:38,785 - madeira.task - ERROR - PROCESS Q2014120514552410003317 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) 1146 (42S02): Table 'madeira.up_order_700116' doesn't exist 'INSERT INTO up_order_700116 (stage, order_id, up_order_id, route, price, cost, up_cost, up_req_time, up_resp_time, up_back_time, up_result, up_back_result) VALUES (%(stage)s, %(order_id)s, %(up_order_id)s, %(route)s, %(price)s, %(cost)s, %(up_cost)s, %(up_req_time)s, %(up_resp_time)s, %(up_back_time)s, %(up_result)s, %(up_back_result)s)' {'price': 30, 'order_id': 'Q2014120514500610003311', 'stage': 1, 'cost': 285000, 'up_back_result': '00000', 'route': '21cn', 'up_order_id': 'Q2014120514500610003311', 'up_result': '0', 'up_back_time': datetime.datetime(2014, 12, 5, 14, 55, 31), 'up_cost': '285000', 'up_resp_time': datetime.datetime(2014, 12, 5, 14, 50, 7), 'up_req_time': datetime.datetime(2014, 12, 5, 14, 50, 6)}
Q2014120514552410003317 回单数据丢失，需要手工补数据 越亮传奇
task-order.log.2014-12-05:2014-12-05 15:34:34,516 - madeira.task - ERROR - PROCESS Q2014120515343010003348 FAIL: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) 1048 (23000): Column 'result' cannot be null 'INSERT INTO order_101001 (order_id, user_id, price, mobile, sp_order_id, req_time, resp_time, back_time, result, back_result, value, balance, area, product) VALUES (%(order_id)s, %(user_id)s, %(price)s, %(mobile)s, %(sp_order_id)s, %(req_time)s, %(resp_time)s, %(back_time)s, %(result)s, %(back_result)s, %(value)s, %(balance)s, %(area)s, %(product)s)' {'area': '2:NX', 'price': 10, 'req_time': datetime.datetime(2014, 12, 5, 15, 34, 28), 'back_result': None, 'sp_order_id': 'zuan_82458141', 'result': None, 'order_id': 'Q2014120515342810003347', 'user_id': '101001', 'mobile': '15595295570', 'value': None, 'product': 'data', 'balance': None, 'back_time': None, 'resp_time': None}
Q2014120515343010003348 Duanfei（order_700107） 在途单保存失败，完工单保存成功，不需要修复 不需要补单


update order_700109 set back_result='00000', back_time='2014-12-05 09:14:40' where order_id='Q2014120509112410003130';
update order_101103 set back_result='99999', back_time='2014-12-05 14:55:30' where order_id='Q2014120514552410003317';
